### ISSUE TITLE
schema.json failed to open stream

### ISSUE THREAD

**Issue by Kibetchirchir** [kaperys/financial#12]
file_put_contents(/var/www/html/project/coopBank/vendor/kaperys/financial/src/Cache/../../cache/ISO8583/schema.json): failed to open stream: No such file or directory

**Comment by jlowder-mps** [comment]
I am having the same issue "failed to open stream: No such file or directory in /var/www/html/vendor/kaperys/financial/src/Cache/CacheManager.php on line 64"

**Comment by kaperys** [comment]
You need to generate the cache file first. See https://github.com/kaperys/financial/blob/master/examples/pack.php#L18

**Comment by jlowder-mps** [comment]
I also had to change line 27 in the CacheManager.php file from:
        'cacheDirectory' => __DIR__ . '/../../cache',
to:
        'cacheDirectory' => __DIR__ . '',

Maybe because I had already created the ISO8583 directory in the cache during troubleshooting? In anycase, it is working for me now. Thanks!
