### ISSUE TITLE
能降低php版本要求么？ 

### ISSUE THREAD

**Issue by he426100** [kaperys/financial#3]
我是5.6.30， 无法使用composer安装这个， 试过把它下下来， 然后用require， 费了九牛二虎之力始终无法正常运行。 php的8583处理类太难找了

**Comment by kaperys** [comment]
Loosely translated this with Google Translate.

> I was 5.6.30, can not use the composer to install this, tried to put it down, and then use require, the effort has never been able to run properly. Php 8583 processing class is too hard to find

Composer installation isn't yet supported, but it will be. The library isn't yet in a completed state (hence all the code being on the 'develop' branch). Once I've got this thing finished and tested, I'll merge to master. Then, Composer installation will work.

**Comment by kaperys** [comment]
@he426100 As of release v0.1-alpha Composer installation is supported.

**Comment by he426100** [comment]
thanks
