### ISSUE TITLE
Kaperys\Financial\Message\Mapper\AlphanumericMapper::pack() must be of the type string, object given

### ISSUE THREAD

**Issue by ozaetaa** [kaperys/financial#7]
Hello,

I tried to do something like 

`use \DateTime;`
`...`
`$localTransactionTime= new DateTime("now");`
`$schemaManager->setLocalTransactionTime($localTransactionTime);`

Upon calling `$message->generate()` it was returning the error `Kaperys\Financial\Message\Mapper\AlphanumericMapper::pack() must be of the type string, object given`.

The type hint for the field says DateTime which I assume is the php DateTime class. Am I missing something ?

**Comment by kaperys** [comment]
@ozaetaa fixed in https://github.com/kaperys/financial/releases/tag/v0.2 :smiley:
